on:
  push:
    branches:
      - master 



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Printing before folder contents'
        run: ls
      - uses: actions/checkout@v3
      - name: 'Printing after folder contents'
      run: ls